---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: people.k8s.terraform.io
spec:
  group: k8s.terraform.io
  names:
    kind: Person
    plural: people
    singular: person
    shortNames:
    - ppl
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          details:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              age:
                type: integer
              status:
                type: string
                default: "inactive"
              org:
                type: string
            required:
            - firstName
            - lastName
            - org
