blank_issues_enabled: false
contact_links:
  - name: Kubernetes Provider for Terraform Roadmap
    url: https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/_about/ROADMAP.md
