name: Issue Opened Triage

on:
  issues:
    types: [opened]
  workflow_dispatch:
  push:
    branches:
      - tfproviderlinttest

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: write
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  issue_triage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Label new issue
      uses: github/issue-labeler@a326d12b9b64d4395a18e50f648214c609501643
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-issue-triage.yml
        enable-versioned-regex: 0
        not-before: 2021-06-01T00:00:00Z
